// This JLex file was machine-generated by the BNF converter
package grammar;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() {return new String(yy_buffer,yy_buffer_index,10).trim();}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		48,
		52,
		52,
		52,
		52,
		52
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NOT_ACCEPT,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NOT_ACCEPT,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NOT_ACCEPT,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NOT_ACCEPT,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NOT_ACCEPT,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR,
		/* 140 */ YY_NO_ANCHOR,
		/* 141 */ YY_NO_ANCHOR,
		/* 142 */ YY_NO_ANCHOR,
		/* 143 */ YY_NO_ANCHOR,
		/* 144 */ YY_NO_ANCHOR,
		/* 145 */ YY_NO_ANCHOR,
		/* 146 */ YY_NO_ANCHOR,
		/* 147 */ YY_NO_ANCHOR,
		/* 148 */ YY_NO_ANCHOR,
		/* 149 */ YY_NO_ANCHOR,
		/* 150 */ YY_NO_ANCHOR,
		/* 151 */ YY_NO_ANCHOR,
		/* 152 */ YY_NO_ANCHOR,
		/* 153 */ YY_NO_ANCHOR,
		/* 154 */ YY_NO_ANCHOR,
		/* 155 */ YY_NO_ANCHOR,
		/* 156 */ YY_NO_ANCHOR,
		/* 157 */ YY_NO_ANCHOR,
		/* 158 */ YY_NO_ANCHOR,
		/* 159 */ YY_NO_ANCHOR,
		/* 160 */ YY_NO_ANCHOR,
		/* 161 */ YY_NO_ANCHOR,
		/* 162 */ YY_NO_ANCHOR,
		/* 163 */ YY_NO_ANCHOR,
		/* 164 */ YY_NO_ANCHOR,
		/* 165 */ YY_NO_ANCHOR,
		/* 166 */ YY_NO_ANCHOR,
		/* 167 */ YY_NO_ANCHOR,
		/* 168 */ YY_NO_ANCHOR,
		/* 169 */ YY_NO_ANCHOR,
		/* 170 */ YY_NO_ANCHOR,
		/* 171 */ YY_NO_ANCHOR,
		/* 172 */ YY_NO_ANCHOR,
		/* 173 */ YY_NO_ANCHOR,
		/* 174 */ YY_NO_ANCHOR,
		/* 175 */ YY_NO_ANCHOR,
		/* 176 */ YY_NO_ANCHOR,
		/* 177 */ YY_NO_ANCHOR,
		/* 178 */ YY_NO_ANCHOR,
		/* 179 */ YY_NO_ANCHOR,
		/* 180 */ YY_NO_ANCHOR,
		/* 181 */ YY_NO_ANCHOR,
		/* 182 */ YY_NO_ANCHOR,
		/* 183 */ YY_NO_ANCHOR,
		/* 184 */ YY_NO_ANCHOR,
		/* 185 */ YY_NO_ANCHOR,
		/* 186 */ YY_NO_ANCHOR,
		/* 187 */ YY_NO_ANCHOR,
		/* 188 */ YY_NO_ANCHOR,
		/* 189 */ YY_NO_ANCHOR,
		/* 190 */ YY_NO_ANCHOR,
		/* 191 */ YY_NO_ANCHOR,
		/* 192 */ YY_NO_ANCHOR,
		/* 193 */ YY_NO_ANCHOR,
		/* 194 */ YY_NO_ANCHOR,
		/* 195 */ YY_NO_ANCHOR,
		/* 196 */ YY_NO_ANCHOR,
		/* 197 */ YY_NO_ANCHOR,
		/* 198 */ YY_NO_ANCHOR,
		/* 199 */ YY_NO_ANCHOR,
		/* 200 */ YY_NO_ANCHOR,
		/* 201 */ YY_NO_ANCHOR,
		/* 202 */ YY_NO_ANCHOR,
		/* 203 */ YY_NO_ANCHOR,
		/* 204 */ YY_NO_ANCHOR,
		/* 205 */ YY_NO_ANCHOR,
		/* 206 */ YY_NO_ANCHOR,
		/* 207 */ YY_NO_ANCHOR,
		/* 208 */ YY_NO_ANCHOR,
		/* 209 */ YY_NO_ANCHOR,
		/* 210 */ YY_NO_ANCHOR,
		/* 211 */ YY_NO_ANCHOR,
		/* 212 */ YY_NO_ANCHOR,
		/* 213 */ YY_NO_ANCHOR,
		/* 214 */ YY_NO_ANCHOR,
		/* 215 */ YY_NO_ANCHOR,
		/* 216 */ YY_NO_ANCHOR,
		/* 217 */ YY_NO_ANCHOR,
		/* 218 */ YY_NO_ANCHOR,
		/* 219 */ YY_NO_ANCHOR,
		/* 220 */ YY_NO_ANCHOR,
		/* 221 */ YY_NO_ANCHOR,
		/* 222 */ YY_NO_ANCHOR,
		/* 223 */ YY_NO_ANCHOR,
		/* 224 */ YY_NO_ANCHOR,
		/* 225 */ YY_NO_ANCHOR,
		/* 226 */ YY_NO_ANCHOR,
		/* 227 */ YY_NO_ANCHOR,
		/* 228 */ YY_NO_ANCHOR,
		/* 229 */ YY_NO_ANCHOR,
		/* 230 */ YY_NO_ANCHOR,
		/* 231 */ YY_NO_ANCHOR,
		/* 232 */ YY_NO_ANCHOR,
		/* 233 */ YY_NO_ANCHOR,
		/* 234 */ YY_NO_ANCHOR,
		/* 235 */ YY_NO_ANCHOR,
		/* 236 */ YY_NO_ANCHOR,
		/* 237 */ YY_NO_ANCHOR,
		/* 238 */ YY_NO_ANCHOR,
		/* 239 */ YY_NO_ANCHOR,
		/* 240 */ YY_NO_ANCHOR,
		/* 241 */ YY_NO_ANCHOR,
		/* 242 */ YY_NO_ANCHOR,
		/* 243 */ YY_NO_ANCHOR,
		/* 244 */ YY_NO_ANCHOR,
		/* 245 */ YY_NO_ANCHOR,
		/* 246 */ YY_NO_ANCHOR,
		/* 247 */ YY_NO_ANCHOR,
		/* 248 */ YY_NO_ANCHOR,
		/* 249 */ YY_NO_ANCHOR,
		/* 250 */ YY_NO_ANCHOR,
		/* 251 */ YY_NO_ANCHOR,
		/* 252 */ YY_NO_ANCHOR,
		/* 253 */ YY_NO_ANCHOR,
		/* 254 */ YY_NO_ANCHOR,
		/* 255 */ YY_NO_ANCHOR,
		/* 256 */ YY_NO_ANCHOR,
		/* 257 */ YY_NO_ANCHOR,
		/* 258 */ YY_NO_ANCHOR,
		/* 259 */ YY_NO_ANCHOR,
		/* 260 */ YY_NO_ANCHOR,
		/* 261 */ YY_NO_ANCHOR,
		/* 262 */ YY_NO_ANCHOR,
		/* 263 */ YY_NO_ANCHOR,
		/* 264 */ YY_NO_ANCHOR,
		/* 265 */ YY_NO_ANCHOR,
		/* 266 */ YY_NO_ANCHOR,
		/* 267 */ YY_NO_ANCHOR,
		/* 268 */ YY_NO_ANCHOR,
		/* 269 */ YY_NO_ANCHOR,
		/* 270 */ YY_NO_ANCHOR,
		/* 271 */ YY_NO_ANCHOR,
		/* 272 */ YY_NO_ANCHOR,
		/* 273 */ YY_NO_ANCHOR,
		/* 274 */ YY_NO_ANCHOR,
		/* 275 */ YY_NO_ANCHOR,
		/* 276 */ YY_NO_ANCHOR,
		/* 277 */ YY_NO_ANCHOR,
		/* 278 */ YY_NO_ANCHOR,
		/* 279 */ YY_NO_ANCHOR,
		/* 280 */ YY_NO_ANCHOR,
		/* 281 */ YY_NO_ANCHOR,
		/* 282 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"48:9,51,46,48,51,45,48:18,51,48:9,47,48,9,5,8,7,19,20,50:8,3,4,48:2,6,48:2," +
"39,10,35,49:2,44,32,49,13,49:2,38,49:3,18,49,43,31,21,33,49,41,49:3,48:4,49" +
",48,11,49,25,12,26,49,28,36,15,49,37,17,30,14,24,27,49,22,23,16,29,40,49,34" +
",42,49,1,48,2,48:66,49:23,48,49:31,48,49:8,48:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,283,
"0,1:5,2,1,3,4,1:2,5,1,6:2,1:2,6,7,6:3,8,6:13,1:4,9,10,11,12,13,14,6,15,16,1" +
"7,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,4" +
"2,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,6" +
"7,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,9" +
"2,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112," +
"113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131" +
",132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,15" +
"0,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,1" +
"69,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187," +
"188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206" +
",6,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224," +
"225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243" +
",244,245,246,247,248")[0];

	private int yy_nxt[][] = unpackFromString(249,52,
"1,2,3,4,5,41,-1,6,44,7,8,197,240,254,261,264,266,267,42,9:2,282,268,269,240" +
",270,271,272,240,273,274,240:14,10:2,-1:2,240,9,10,-1:59,46,-1:39,12,-1:14," +
"240,45,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,9:2,240:24,-1:4,240,9,-1:4" +
"8,17,-1:14,240:9,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:18,80,240:5,-" +
"1:4,240,47,-1:11,240:9,47:2,240:10,117,240:13,-1:4,240,47,-1:7,11,-1:55,240" +
":9,14,15,240:24,-1:4,240,47,-1:8,39,-1:39,50,-1:12,13,-1:53,240:2,18,240:6," +
"47:2,240:24,-1:4,240,47,-1:2,46:45,16,46:5,1,37:44,-1,38,43,37:4,-1:10,240:" +
"9,47:2,240:4,202,240:19,-1:4,240,47,-1:8,40,-1:54,240:6,63,240:2,47:2,240:2" +
"4,-1:4,240,47,-1,1,-1:61,240:5,64,240:3,47:2,240:24,-1:4,240,47,-1:11,240:8" +
",201,47:2,240:24,-1:4,240,47,-1:11,240,203,240:7,47:2,240:24,-1:4,240,47,-1" +
":11,240:9,47:2,240:3,66,240:3,67,240:16,-1:4,240,47,-1:11,240:9,47:2,240:9," +
"200,240:14,-1:4,240,47,-1:11,240:9,47:2,240:3,69,240:20,-1:4,240,47,-1:11,2" +
"40:9,47:2,240:6,70,240:17,-1:4,240,47,-1:11,240:9,47:2,240,204,240:22,-1:4," +
"240,47,-1:11,240:9,47:2,240:5,71,240:18,-1:4,240,47,-1:11,240:4,72,240:4,47" +
":2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:3,241,240:20,-1:4,240,47,-1:11,2" +
"40:6,74,240:2,47:2,240:24,-1:4,240,47,-1:11,240:6,19,240:2,47:2,240:24,-1:4" +
",240,47,-1:11,240:9,47:2,240:6,20,240:17,-1:4,240,47,-1:11,240:9,47:2,240:1" +
"7,207,240:6,-1:4,240,47,-1:11,240,76,240:7,47:2,240:24,-1:4,240,47,-1:11,24" +
"0:9,47:2,240:2,256,240:21,-1:4,240,47,-1:11,240:7,206,240,47:2,240:24,-1:4," +
"240,47,-1:11,240:9,47:2,240:22,78,240,-1:4,240,47,-1:11,240:9,47:2,240:3,20" +
"8,240:20,-1:4,240,47,-1:11,240:9,47:2,240:6,276,240:17,-1:4,240,47,-1:11,24" +
"0:5,245,240:3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:5,79,240:18,-1:4" +
",240,47,-1:11,240:6,211,240:2,47:2,240:24,-1:4,240,47,-1:11,240:7,244,240,4" +
"7:2,240:24,-1:4,240,47,-1:11,240,86,240:7,47:2,240:24,-1:4,240,47,-1:11,240" +
":9,47:2,240:4,275,240:19,-1:4,240,47,-1:11,240:9,47:2,240:8,88,240:15,-1:4," +
"240,47,-1:11,240:2,89,240:6,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:19" +
",90,240:4,-1:4,240,47,-1:11,240:5,247,240:3,47:2,240:24,-1:4,240,47,-1:11,2" +
"40:6,92,240:2,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:4,94,240:19,-1:4" +
",240,47,-1:11,240:4,95,240:4,47:2,240:24,-1:4,240,47,-1:11,240:7,21,240,47:" +
"2,240:24,-1:4,240,47,-1:11,240:6,280,240:2,47:2,240:24,-1:4,240,47,-1:11,24" +
"0:9,47:2,240:8,98,240:15,-1:4,240,47,-1:11,240:9,47:2,240:5,99,240:18,-1:4," +
"240,47,-1:11,240:9,47:2,240:3,100,240:20,-1:4,240,47,-1:11,240:9,47:2,240,2" +
"48,240:22,-1:4,240,47,-1:11,240:9,47:2,240:12,217,240:11,-1:4,240,47,-1:11," +
"240:5,216,240:3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:16,102,240:7,-" +
"1:4,240,47,-1:11,240:6,103,240:2,47:2,240:24,-1:4,240,47,-1:11,240:4,104,24" +
"0:4,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:4,107,240:19,-1:4,240,47,-" +
"1:11,240:7,22,240,47:2,240:24,-1:4,240,47,-1:11,240:4,23,240:4,47:2,240:24," +
"-1:4,240,47,-1:11,240:7,24,240,47:2,240:24,-1:4,240,47,-1:11,240:5,218,240:" +
"3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:15,111,240:8,-1:4,240,47,-1:" +
"11,240:9,47:2,240:7,25,240:16,-1:4,240,47,-1:11,240:4,112,240:4,47:2,240:24" +
",-1:4,240,47,-1:11,240:9,47:2,240:6,113,240:17,-1:4,240,47,-1:11,240:9,47:2" +
",240:5,115,240:18,-1:4,240,47,-1:11,240:9,47:2,240:3,116,240:20,-1:4,240,47" +
",-1:11,240:2,119,240:6,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:14,120," +
"240:9,-1:4,240,47,-1:11,240:5,122,240:3,47:2,240:24,-1:4,240,47,-1:11,240:9" +
",47:2,240:10,277,240:13,-1:4,240,47,-1:11,240:9,47:2,240:8,220,240:15,-1:4," +
"240,47,-1:11,240,249,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240,123" +
",240:22,-1:4,240,47,-1:11,240:4,26,240:4,47:2,240:24,-1:4,240,47,-1:11,240:" +
"6,124,240:2,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:2,27,240:21,-1:4,2" +
"40,47,-1:11,240:9,47:2,240:5,125,240:18,-1:4,240,47,-1:11,240:9,47:2,240:15" +
",126,240:8,-1:4,240,47,-1:11,240:9,47:2,240:7,127,240:16,-1:4,240,47,-1:11," +
"240:9,47:2,240:4,128,240:19,-1:4,240,47,-1:11,240:9,47:2,240:10,130,240:13," +
"-1:4,240,47,-1:11,240,222,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,24" +
"0,131,240:22,-1:4,240,47,-1:11,240:9,47:2,240:5,132,240:18,-1:4,240,47,-1:1" +
"1,240:9,47:2,240:23,133,-1:4,240,47,-1:11,240:9,47:2,240:20,134,240:3,-1:4," +
"240,47,-1:11,240:9,47:2,240:3,136,240:20,-1:4,240,47,-1:11,240:6,137,240:2," +
"47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,139,240:23,-1:4,240,47,-1:11,240:9" +
",47:2,240:4,140,240:19,-1:4,240,47,-1:11,240:9,47:2,240:8,225,240:15,-1:4,2" +
"40,47,-1:11,240:5,226,240:3,47:2,240:24,-1:4,240,47,-1:11,240:2,142,240:6,4" +
"7:2,240:24,-1:4,240,47,-1:11,240:4,143,240:4,47:2,240:24,-1:4,240,47,-1:11," +
"240,250,240:7,47:2,240:24,-1:4,240,47,-1:11,240:6,144,240:2,47:2,240:24,-1:" +
"4,240,47,-1:11,240:9,47:2,240,145,240:22,-1:4,240,47,-1:11,240:9,47:2,240:1" +
"6,146,240:7,-1:4,240,47,-1:11,240:9,47:2,240:5,149,240:18,-1:4,240,47,-1:11" +
",240:3,227,240:5,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:10,150,240:13" +
",-1:4,240,47,-1:11,240:5,251,240:3,47:2,240:24,-1:4,240,47,-1:11,240,259,24" +
"0:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:2,152,240:21,-1:4,240,47,-" +
"1:11,240:9,47:2,240:4,228,240:19,-1:4,240,47,-1:11,240:4,229,240:4,47:2,240" +
":24,-1:4,240,47,-1:11,240:9,47:2,240:11,153,240:12,-1:4,240,47,-1:11,240:6," +
"155,240:2,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:5,156,240:18,-1:4,24" +
"0,47,-1:11,240:9,47:2,240:12,159,240:11,-1:4,240,47,-1:11,240:9,47:2,240:8," +
"161,240:15,-1:4,240,47,-1:11,240:9,47:2,240:19,230,240:4,-1:4,240,47,-1:11," +
"240,162,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:11,163,240:12,-1" +
":4,240,47,-1:11,240:9,47:2,240:7,164,240:16,-1:4,240,47,-1:11,240:9,47:2,24" +
"0:2,232,240:21,-1:4,240,47,-1:11,240:4,233,240:4,47:2,240:24,-1:4,240,47,-1" +
":11,240:5,165,240:3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:5,167,240:" +
"18,-1:4,240,47,-1:11,240:6,169,240:2,47:2,240:24,-1:4,240,47,-1:11,240:9,47" +
":2,240:8,170,240:15,-1:4,240,47,-1:11,240:9,47:2,240:20,171,240:3,-1:4,240," +
"47,-1:11,240:9,47:2,240:3,174,240:20,-1:4,240,47,-1:11,240:9,47:2,240:2,28," +
"240:21,-1:4,240,47,-1:11,240:9,47:2,240:2,234,240:21,-1:4,240,47,-1:11,240:" +
"9,47:2,240,235,240:22,-1:4,240,47,-1:11,240:9,47:2,240:5,175,240:18,-1:4,24" +
"0,47,-1:11,240:9,47:2,240:5,252,240:18,-1:4,240,47,-1:11,240:5,236,240:3,47" +
":2,240:24,-1:4,240,47,-1:11,240:6,176,240:2,47:2,240:24,-1:4,240,47,-1:11,2" +
"40:5,257,240:3,47:2,240:24,-1:4,240,47,-1:11,240:4,177,240:4,47:2,240:24,-1" +
":4,240,47,-1:11,240:9,47:2,240:11,179,240:12,-1:4,240,47,-1:11,240:5,181,24" +
"0:3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:2,29,240:21,-1:4,240,47,-1" +
":11,240,238,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:8,278,240:15" +
",-1:4,240,47,-1:11,240:9,47:2,240:15,30,240:8,-1:4,240,47,-1:11,240:9,47:2," +
"240:3,253,240:20,-1:4,240,47,-1:11,240:9,47:2,240:17,185,240:6,-1:4,240,47," +
"-1:11,240:4,186,240:4,47:2,240:24,-1:4,240,47,-1:11,240:5,188,240:3,47:2,24" +
"0:24,-1:4,240,47,-1:11,240:9,47:2,240:5,239,240:18,-1:4,240,47,-1:11,240:9," +
"47:2,240:7,31,240:16,-1:4,240,47,-1:11,240:6,32,240:2,47:2,240:24,-1:4,240," +
"47,-1:11,240:4,190,240:4,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:2,33," +
"240:21,-1:4,240,47,-1:11,240:9,47:2,240:7,34,240:16,-1:4,240,47,-1:11,240:9" +
",47:2,240:7,193,240:16,-1:4,240,47,-1:11,240:5,194,240:3,47:2,240:24,-1:4,2" +
"40,47,-1:11,240:6,195,240:2,47:2,240:24,-1:4,240,47,-1:11,240:4,196,240:4,4" +
"7:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:15,35,240:8,-1:4,240,47,-1:11,2" +
"40:9,47:2,240:7,36,240:16,-1:4,240,47,-1:11,240:9,47:2,240:4,49,240:3,51,24" +
"0:15,-1:4,240,47,-1:11,240:6,68,240:2,47:2,240:24,-1:4,240,47,-1:11,240:5,6" +
"5,240:3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:9,243,240:14,-1:4,240," +
"47,-1:11,240:9,47:2,240,75,240:22,-1:4,240,47,-1:11,240:9,47:2,240:5,73,240" +
":18,-1:4,240,47,-1:11,240:4,205,240:4,47:2,240:24,-1:4,240,47,-1:11,240,77," +
"240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:2,81,240:21,-1:4,240,47," +
"-1:11,240:5,85,240:3,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:5,82,240:" +
"18,-1:4,240,47,-1:11,240:7,246,240,47:2,240:24,-1:4,240,47,-1:11,240,212,24" +
"0:7,47:2,240:24,-1:4,240,47,-1:11,240:2,93,240:6,47:2,240:24,-1:4,240,47,-1" +
":11,240:5,91,240:3,47:2,240:24,-1:4,240,47,-1:11,240:6,214,240:2,47:2,240:2" +
"4,-1:4,240,47,-1:11,240:9,47:2,240:5,101,240:18,-1:4,240,47,-1:11,240:9,47:" +
"2,240:3,105,240:20,-1:4,240,47,-1:11,240:5,108,240:3,47:2,240:24,-1:4,240,4" +
"7,-1:11,240:6,110,240:2,47:2,240:24,-1:4,240,47,-1:11,240:4,109,240:4,47:2," +
"240:24,-1:4,240,47,-1:11,240:4,121,240:4,47:2,240:24,-1:4,240,47,-1:11,240:" +
"9,47:2,240:5,118,240:18,-1:4,240,47,-1:11,240:6,223,240:2,47:2,240:24,-1:4," +
"240,47,-1:11,240,224,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240,138" +
",240:22,-1:4,240,47,-1:11,240:9,47:2,240:5,135,240:18,-1:4,240,47,-1:11,240" +
":6,141,240:2,47:2,240:24,-1:4,240,47,-1:11,240:4,147,240:4,47:2,240:24,-1:4" +
",240,47,-1:11,240:6,148,240:2,47:2,240:24,-1:4,240,47,-1:11,240:4,154,240:4" +
",47:2,240:24,-1:4,240,47,-1:11,240:6,160,240:2,47:2,240:24,-1:4,240,47,-1:1" +
"1,240:9,47:2,240:5,231,240:18,-1:4,240,47,-1:11,240,168,240:7,47:2,240:24,-" +
"1:4,240,47,-1:11,240:9,47:2,240:2,166,240:21,-1:4,240,47,-1:11,240:5,172,24" +
"0:3,47:2,240:24,-1:4,240,47,-1:11,240:6,173,240:2,47:2,240:24,-1:4,240,47,-" +
"1:11,240:9,47:2,240:2,237,240:21,-1:4,240,47,-1:11,240:5,178,240:3,47:2,240" +
":24,-1:4,240,47,-1:11,240:6,180,240:2,47:2,240:24,-1:4,240,47,-1:11,240:5,1" +
"83,240:3,47:2,240:24,-1:4,240,47,-1:11,240:4,187,240:4,47:2,240:24,-1:4,240" +
",47,-1:11,240:4,191,240:4,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:9,20" +
"9,240:14,-1:4,240,47,-1:11,240:9,47:2,240:2,83,240:21,-1:4,240,47,-1:11,240" +
":9,47:2,240:5,84,240:18,-1:4,240,47,-1:11,240:7,213,240,47:2,240:24,-1:4,24" +
"0,47,-1:11,240,87,240:7,47:2,240:24,-1:4,240,47,-1:11,240:5,96,240:3,47:2,2" +
"40:24,-1:4,240,47,-1:11,240:6,215,240:2,47:2,240:24,-1:4,240,47,-1:11,240:5" +
",219,240:3,47:2,240:24,-1:4,240,47,-1:11,240:6,129,240:2,47:2,240:24,-1:4,2" +
"40,47,-1:11,240:6,151,240:2,47:2,240:24,-1:4,240,47,-1:11,240:4,157,240:4,4" +
"7:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240:2,260,240:21,-1:4,240,47,-1:11," +
"240:4,189,240:4,47:2,240:24,-1:4,240,47,-1:11,240:4,53,240:4,47:2,240:24,-1" +
":4,240,47,-1:11,240:9,47:2,240:9,106,240:14,-1:4,240,47,-1:11,240:9,47:2,24" +
"0:5,210,240:18,-1:4,240,47,-1:11,240:7,182,240,47:2,240:24,-1:4,240,47,-1:1" +
"1,240:5,97,240:3,47:2,240:24,-1:4,240,47,-1:11,240:4,158,240:4,47:2,240:24," +
"-1:4,240,47,-1:11,240:9,47:2,240:2,184,240:21,-1:4,240,47,-1:11,240:9,47:2," +
"240:3,54,240:20,-1:4,240,47,-1:11,240:9,47:2,240:9,114,240:14,-1:4,240,47,-" +
"1:11,240:9,47:2,240:2,265,240:21,-1:4,240,47,-1:11,240:4,199,240:4,47:2,240" +
":24,-1:4,240,47,-1:11,240:9,47:2,240:2,192,240:21,-1:4,240,47,-1:11,240:9,4" +
"7:2,240,55,240:22,-1:4,240,47,-1:11,240:9,47:2,240:3,56,240:20,-1:4,240,47," +
"-1:11,240:9,47:2,240:3,198,240:20,-1:4,240,47,-1:11,240:9,47:2,240:21,57,24" +
"0:2,-1:4,240,47,-1:11,240:7,58,240,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2" +
",240:13,59,240:10,-1:4,240,47,-1:11,240,60,240:7,47:2,240:24,-1:4,240,47,-1" +
":11,240:9,47:2,240:2,61,240:21,-1:4,240,47,-1:11,240:9,47:2,240:3,62,240:20" +
",-1:4,240,47,-1:11,240:9,47:2,240:3,255,240:20,-1:4,240,47,-1:11,240:6,258," +
"240:2,47:2,240:24,-1:4,240,47,-1:11,240:6,221,240:2,47:2,240:24,-1:4,240,47" +
",-1:11,240:9,47:2,240:5,263,240:18,-1:4,240,47,-1:11,240:4,242,240:4,47:2,2" +
"40:24,-1:4,240,47,-1:11,240:9,47:2,240:3,262,240:20,-1:4,240,47,-1:11,240,2" +
"79,240:7,47:2,240:24,-1:4,240,47,-1:11,240:9,47:2,240,281,240:22,-1:4,240,4" +
"7,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_2); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_3); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_5); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_7); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -9:
						break;
					case 9:
						{ return new Symbol(sym.MyInteger, yytext().intern()); }
					case -10:
						break;
					case 10:
						{ /* ignore white space. */ }
					case -11:
						break;
					case 11:
						{ return new Symbol(sym._SYMB_4); }
					case -12:
						break;
					case 12:
						{ yybegin(COMMENT); }
					case -13:
						break;
					case 13:
						{ return new Symbol(sym._SYMB_6); }
					case -14:
						break;
					case 14:
						{ return new Symbol(sym._SYMB_10); }
					case -15:
						break;
					case 15:
						{ return new Symbol(sym._SYMB_11); }
					case -16:
						break;
					case 16:
						{ /* BNFC single-line comment */ }
					case -17:
						break;
					case 17:
						{ yybegin(COMMENT); }
					case -18:
						break;
					case 18:
						{ return new Symbol(sym._SYMB_8); }
					case -19:
						break;
					case 19:
						{ return new Symbol(sym._SYMB_17); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_20); }
					case -21:
						break;
					case 21:
						{ return new Symbol(sym._SYMB_9); }
					case -22:
						break;
					case 22:
						{ return new Symbol(sym._SYMB_19); }
					case -23:
						break;
					case 23:
						{ return new Symbol(sym._SYMB_24); }
					case -24:
						break;
					case 24:
						{ return new Symbol(sym._SYMB_23); }
					case -25:
						break;
					case 25:
						{ return new Symbol(sym._SYMB_13); }
					case -26:
						break;
					case 26:
						{ return new Symbol(sym._SYMB_12); }
					case -27:
						break;
					case 27:
						{ return new Symbol(sym._SYMB_26); }
					case -28:
						break;
					case 28:
						{ return new Symbol(sym._SYMB_21); }
					case -29:
						break;
					case 29:
						{ return new Symbol(sym._SYMB_28); }
					case -30:
						break;
					case 30:
						{ return new Symbol(sym._SYMB_25); }
					case -31:
						break;
					case 31:
						{ return new Symbol(sym._SYMB_14); }
					case -32:
						break;
					case 32:
						{ return new Symbol(sym._SYMB_22); }
					case -33:
						break;
					case 33:
						{ return new Symbol(sym._SYMB_15); }
					case -34:
						break;
					case 34:
						{ return new Symbol(sym._SYMB_27); }
					case -35:
						break;
					case 35:
						{ return new Symbol(sym._SYMB_16); }
					case -36:
						break;
					case 36:
						{ return new Symbol(sym._SYMB_18); }
					case -37:
						break;
					case 37:
						{ }
					case -38:
						break;
					case 38:
						{ }
					case -39:
						break;
					case 39:
						{ yybegin(YYINITIAL); }
					case -40:
						break;
					case 40:
						{ yybegin(YYINITIAL); }
					case -41:
						break;
					case 42:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -42:
						break;
					case 43:
						{ }
					case -43:
						break;
					case 45:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -44:
						break;
					case 47:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -45:
						break;
					case 49:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -46:
						break;
					case 51:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -47:
						break;
					case 53:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -48:
						break;
					case 54:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -49:
						break;
					case 55:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -50:
						break;
					case 56:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -51:
						break;
					case 57:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -52:
						break;
					case 58:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -53:
						break;
					case 59:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -54:
						break;
					case 60:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -55:
						break;
					case 61:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -56:
						break;
					case 62:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -57:
						break;
					case 63:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -58:
						break;
					case 64:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -59:
						break;
					case 65:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -60:
						break;
					case 66:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -61:
						break;
					case 67:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -62:
						break;
					case 68:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -63:
						break;
					case 69:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -64:
						break;
					case 70:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -65:
						break;
					case 71:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -66:
						break;
					case 72:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -67:
						break;
					case 73:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -68:
						break;
					case 74:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -69:
						break;
					case 75:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -70:
						break;
					case 76:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -71:
						break;
					case 77:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -72:
						break;
					case 78:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -73:
						break;
					case 79:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -74:
						break;
					case 80:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -75:
						break;
					case 81:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -76:
						break;
					case 82:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -77:
						break;
					case 83:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -78:
						break;
					case 84:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -79:
						break;
					case 85:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -80:
						break;
					case 86:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -81:
						break;
					case 87:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -82:
						break;
					case 88:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -83:
						break;
					case 89:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -84:
						break;
					case 90:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -85:
						break;
					case 91:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -86:
						break;
					case 92:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -87:
						break;
					case 93:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -88:
						break;
					case 94:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -89:
						break;
					case 95:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -90:
						break;
					case 96:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -91:
						break;
					case 97:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -92:
						break;
					case 98:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -93:
						break;
					case 99:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -94:
						break;
					case 100:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -95:
						break;
					case 101:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -96:
						break;
					case 102:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -97:
						break;
					case 103:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -98:
						break;
					case 104:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -99:
						break;
					case 105:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -100:
						break;
					case 106:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -101:
						break;
					case 107:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -102:
						break;
					case 108:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -103:
						break;
					case 109:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -104:
						break;
					case 110:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -105:
						break;
					case 111:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -106:
						break;
					case 112:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -107:
						break;
					case 113:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -108:
						break;
					case 114:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -109:
						break;
					case 115:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -110:
						break;
					case 116:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -111:
						break;
					case 117:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -112:
						break;
					case 118:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -113:
						break;
					case 119:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -114:
						break;
					case 120:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -115:
						break;
					case 121:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -116:
						break;
					case 122:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -117:
						break;
					case 123:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -118:
						break;
					case 124:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -119:
						break;
					case 125:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -120:
						break;
					case 126:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -121:
						break;
					case 127:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -122:
						break;
					case 128:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -123:
						break;
					case 129:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -124:
						break;
					case 130:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -125:
						break;
					case 131:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -126:
						break;
					case 132:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -127:
						break;
					case 133:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -128:
						break;
					case 134:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -129:
						break;
					case 135:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -130:
						break;
					case 136:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -131:
						break;
					case 137:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -132:
						break;
					case 138:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -133:
						break;
					case 139:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -134:
						break;
					case 140:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -135:
						break;
					case 141:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -136:
						break;
					case 142:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -137:
						break;
					case 143:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -138:
						break;
					case 144:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -139:
						break;
					case 145:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -140:
						break;
					case 146:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -141:
						break;
					case 147:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -142:
						break;
					case 148:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -143:
						break;
					case 149:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -144:
						break;
					case 150:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -145:
						break;
					case 151:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -146:
						break;
					case 152:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -147:
						break;
					case 153:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -148:
						break;
					case 154:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -149:
						break;
					case 155:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -150:
						break;
					case 156:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -151:
						break;
					case 157:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -152:
						break;
					case 158:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -153:
						break;
					case 159:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -154:
						break;
					case 160:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -155:
						break;
					case 161:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -156:
						break;
					case 162:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -157:
						break;
					case 163:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -158:
						break;
					case 164:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -159:
						break;
					case 165:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -160:
						break;
					case 166:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -161:
						break;
					case 167:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -162:
						break;
					case 168:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -163:
						break;
					case 169:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -164:
						break;
					case 170:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -165:
						break;
					case 171:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -166:
						break;
					case 172:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -167:
						break;
					case 173:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -168:
						break;
					case 174:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -169:
						break;
					case 175:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -170:
						break;
					case 176:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -171:
						break;
					case 177:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -172:
						break;
					case 178:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -173:
						break;
					case 179:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -174:
						break;
					case 180:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -175:
						break;
					case 181:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -176:
						break;
					case 182:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -177:
						break;
					case 183:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -178:
						break;
					case 184:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -179:
						break;
					case 185:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -180:
						break;
					case 186:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -181:
						break;
					case 187:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -182:
						break;
					case 188:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -183:
						break;
					case 189:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -184:
						break;
					case 190:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -185:
						break;
					case 191:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -186:
						break;
					case 192:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -187:
						break;
					case 193:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -188:
						break;
					case 194:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -189:
						break;
					case 195:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -190:
						break;
					case 196:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -191:
						break;
					case 197:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -192:
						break;
					case 198:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -193:
						break;
					case 199:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -194:
						break;
					case 200:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -195:
						break;
					case 201:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -196:
						break;
					case 202:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -197:
						break;
					case 203:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -198:
						break;
					case 204:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -199:
						break;
					case 205:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -200:
						break;
					case 206:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -201:
						break;
					case 207:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -202:
						break;
					case 208:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -203:
						break;
					case 209:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -204:
						break;
					case 210:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -205:
						break;
					case 211:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -206:
						break;
					case 212:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -207:
						break;
					case 213:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -208:
						break;
					case 214:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -209:
						break;
					case 215:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -210:
						break;
					case 216:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -211:
						break;
					case 217:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -212:
						break;
					case 218:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -213:
						break;
					case 219:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -214:
						break;
					case 220:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -215:
						break;
					case 221:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -216:
						break;
					case 222:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -217:
						break;
					case 223:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -218:
						break;
					case 224:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -219:
						break;
					case 225:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -220:
						break;
					case 226:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -221:
						break;
					case 227:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -222:
						break;
					case 228:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -223:
						break;
					case 229:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -224:
						break;
					case 230:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -225:
						break;
					case 231:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -226:
						break;
					case 232:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -227:
						break;
					case 233:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -228:
						break;
					case 234:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -229:
						break;
					case 235:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -230:
						break;
					case 236:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -231:
						break;
					case 237:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -232:
						break;
					case 238:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -233:
						break;
					case 239:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -234:
						break;
					case 240:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -235:
						break;
					case 241:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -236:
						break;
					case 242:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -237:
						break;
					case 243:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -238:
						break;
					case 244:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -239:
						break;
					case 245:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -240:
						break;
					case 246:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -241:
						break;
					case 247:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -242:
						break;
					case 248:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -243:
						break;
					case 249:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -244:
						break;
					case 250:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -245:
						break;
					case 251:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -246:
						break;
					case 252:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -247:
						break;
					case 253:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -248:
						break;
					case 254:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -249:
						break;
					case 255:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -250:
						break;
					case 256:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -251:
						break;
					case 257:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -252:
						break;
					case 258:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -253:
						break;
					case 259:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -254:
						break;
					case 260:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -255:
						break;
					case 261:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -256:
						break;
					case 262:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -257:
						break;
					case 263:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -258:
						break;
					case 264:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -259:
						break;
					case 265:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -260:
						break;
					case 266:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -261:
						break;
					case 267:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -262:
						break;
					case 268:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -263:
						break;
					case 269:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -264:
						break;
					case 270:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -265:
						break;
					case 271:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -266:
						break;
					case 272:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -267:
						break;
					case 273:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -268:
						break;
					case 274:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -269:
						break;
					case 275:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -270:
						break;
					case 276:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -271:
						break;
					case 277:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -272:
						break;
					case 278:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -273:
						break;
					case 279:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -274:
						break;
					case 280:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -275:
						break;
					case 281:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -276:
						break;
					case 282:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -277:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
